### ISSUE TITLE
add e.xec.sh

### ISSUE THREAD

**Issue by mattLLVW** [chubin/awesome-console-services#46]
Hey,
Could you add e.xec.sh ? it's some silly console services i wrote. maybe in a useless or random section? :)
```bash
curl e.xec.sh/thankyou
```

**Comment by chubin** [comment]
Yes sure, what URL should be add?

```
curl e.xec.sh
```

delivers HTML, and not terminal output

**Comment by mattLLVW** [comment]
maybe:
```bash
curl e.xec.sh/magic
```
i definitely should return a random gif instead of the static site when _curling_, thanks for pointing that out! :)

**Comment by chubin** [comment]
And maybe some info about usage
(help etc.)
For example, how to get list of the available gifs

**Comment by chubin** [comment]
Please ping me as soon as you've fixed it

**Comment by mattLLVW** [comment]
@chubin it's done

**Comment by chubin** [comment]
@mattLLVW It works very good. I like it. I don't know if it can handle load? Are you ok if I tweet about it? It may generate some load though (not necessarily but it may happen).

Also, I have a feature request:
could it be possible to add some option to narrow the search with the maximum pic width?
then you could use something like:
```
curl e.xec.sh/thank_you?max=$COLUMNS
```

**Comment by mattLLVW** [comment]
@chubin i'm glad you like it.
It should be able to handle load (there's a rate limiter and a cache) so please feel free to tweet about it.

This feature request should be easy enough, i'll look into it.
Thanks!
