### ISSUE TITLE
Five services that are down or unresponsive

### ISSUE THREAD

**Issue by mcthomas** [chubin/awesome-console-services#53]
`ssh brow.sh`

`http://frcl.de/gulasch`

`curl moneroj.org`

`curl cmc.rjldev.com`

`curl -s https://uinames.com/api/?region=france\&amount=25 | jq '.[] | .name +" " + .surname'` ← also tried w/ double quotes for zsh as well

**Comment by chubin** [comment]
Actually, we have automatic test, that controls availability of the services
See #36 for details.

It is not yet fully implemented though.
The idea is to mark unavailable services with :no_entry_sign:
instead of removing them, because it is possible,
that the services are unavailable only temporary

**Comment by mcthomas** [comment]
Ah, that’s a brilliant system, I did wonder whether removed services were truly decommissioned or only offline for some time.  Thanks for informing me.

**Comment by chubin** [comment]
The implementation is not finished, because @lakuapik who was doing the implementation disappeared. Hopefully he will come back soon
