### ISSUE TITLE
termbin.com

### ISSUE THREAD

**Issue by mazeto** [chubin/awesome-console-services#8]
# termbin.com is another text file sharing service
> - termbin.com
# Sorry for filing an issue instead of sending a PR. I'm not a big fan of the fork/PR method.

**Comment by chubin** [comment]
How can I use it from the console?

**Comment by vitalyavolyn** [comment]
There's an example on the site:
```
echo Hello world! | nc termbin.com 9999
```

**Comment by chubin** [comment]
Thank you very much, guys!
